management:
  endpoints:
    web:
      base-path: /

google:
  ai:
    api-key: "AIzaSyDTDwuDUww53A8Xtgv59d47BKQ-Vt-XoOQ"

spring:
  application:
    name: api-server

  datasource:
    url: jdbc:mysql://kummit4-database-1.c1gkogwae7kq.ap-northeast-2.rds.amazonaws.com:3306/kummit_database
    username: admin
    password: kummit4kummit4!

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
