name: CI (Gradle)

on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ☕️ set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: add application.yml to directory
        run: echo "${{ secrets.APPLICATION_YML }}" > application.yml

      - name: grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build with Gradle(without test)
        run: ./gradlew clean build -x test --stacktrace